"""add_operations_models

Revision ID: 16fb4bfba6c5
Revises: cecb309ff3b8
Create Date: 2026-08-08 13:15:10.309089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fb4bfba6c5'
down_revision: Union[str, Sequence[str], None] = 'cecb309ff3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['product_assets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_reports_asset_id'), 'damage_reports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_damage_reports_organization_id'), 'damage_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_damage_reports_rental_id'), 'damage_reports', ['rental_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_damage_reports_rental_id'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_organization_id'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_asset_id'), table_name='damage_reports')
    op.drop_table('damage_reports')
    # ### end Alembic commands ###
