"""add_offline_sync

Revision ID: 21fac9fa4da4
Revises: 798a5c9ad1bf
Create Date: 2026-08-08 14:38:54.061674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21fac9fa4da4'
down_revision: Union[str, Sequence[str], None] = '798a5c9ad1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='offlineactionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_actions_action_id'), 'offline_actions', ['action_id'], unique=True)
    op.create_index(op.f('ix_offline_actions_organization_id'), 'offline_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_offline_actions_rental_id'), 'offline_actions', ['rental_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offline_actions_rental_id'), table_name='offline_actions')
    op.drop_index(op.f('ix_offline_actions_organization_id'), table_name='offline_actions')
    op.drop_index(op.f('ix_offline_actions_action_id'), table_name='offline_actions')
    op.drop_table('offline_actions')
    # ### end Alembic commands ###
