"""add_maintenance

Revision ID: 783e56f70845
Revises: a66100eb0882
Create Date: 2026-08-08 13:18:47.627217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783e56f70845'
down_revision: Union[str, Sequence[str], None] = 'a66100eb0882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('issue', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['product_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tickets_asset_id'), 'maintenance_tickets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_organization_id'), 'maintenance_tickets', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_tickets_organization_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_asset_id'), table_name='maintenance_tickets')
    op.drop_table('maintenance_tickets')
    # ### end Alembic commands ###
