"""fix_trust_fk

Revision ID: 798a5c9ad1bf
Revises: 8cb26028c064
Create Date: 2026-08-08 14:25:47.063352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798a5c9ad1bf'
down_revision: Union[str, Sequence[str], None] = '8cb26028c064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customer_trusts_customer_id_fkey'), 'customer_trusts', type_='foreignkey')
    op.create_foreign_key(None, 'customer_trusts', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_trusts', type_='foreignkey')
    op.create_foreign_key(op.f('customer_trusts_customer_id_fkey'), 'customer_trusts', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
