"""Add products and assets

Revision ID: 874a2dea687b
Revises: 82dd545fd880
Create Date: 2026-08-08 11:54:51.586478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874a2dea687b'
down_revision: Union[str, Sequence[str], None] = '82dd545fd880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('CAMERA', 'PROJECTOR', 'AUDIO', 'GENERATOR', 'LAPTOP', name='productcategory'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('base_rental_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('security_deposit_configuration', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('price_adjustment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_organization_id'), 'product_variants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_table('product_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'READY_FOR_PICKUP', 'ACTIVE', 'RETURN_INSPECTION', 'MAINTENANCE', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('condition', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'DAMAGED', 'CRITICAL', name='assetcondition'), nullable=False),
    sa.Column('rental_count', sa.Integer(), nullable=False),
    sa.Column('last_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'asset_code', name='uq_org_asset_code'),
    sa.UniqueConstraint('organization_id', 'serial_number', name='uq_org_serial_number')
    )
    op.create_index(op.f('ix_product_assets_asset_code'), 'product_assets', ['asset_code'], unique=False)
    op.create_index(op.f('ix_product_assets_organization_id'), 'product_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_assets_product_id'), 'product_assets', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_assets_qr_token'), 'product_assets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_product_assets_serial_number'), 'product_assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_product_assets_variant_id'), 'product_assets', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_assets_variant_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_serial_number'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_qr_token'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_product_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_organization_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_asset_code'), table_name='product_assets')
    op.drop_table('product_assets')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_organization_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
