"""Add protection plan fields

Revision ID: 8cb26028c064
Revises: fa3bb27e3c30
Create Date: 2026-08-08 13:58:47.306421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb26028c064'
down_revision: Union[str, Sequence[str], None] = 'fa3bb27e3c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('has_protection_plan', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('rentals', sa.Column('protection_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('rentals', sa.Column('protection_limit', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'protection_limit')
    op.drop_column('rentals', 'protection_fee')
    op.drop_column('rentals', 'has_protection_plan')
    # ### end Alembic commands ###
