"""Add rental extensions

Revision ID: 96e6767f7e1d
Revises: 722dbb7e19e8
Create Date: 2026-08-08 13:51:12.011101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e6767f7e1d'
down_revision: Union[str, Sequence[str], None] = '722dbb7e19e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('previous_end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('additional_days', sa.Integer(), nullable=False),
    sa.Column('additional_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_extensions_rental_id'), 'rental_extensions', ['rental_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_extensions_rental_id'), table_name='rental_extensions')
    op.drop_table('rental_extensions')
    # ### end Alembic commands ###
