"""add_trust_models

Revision ID: a66100eb0882
Revises: 16fb4bfba6c5
Create Date: 2026-08-08 13:17:22.059831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66100eb0882'
down_revision: Union[str, Sequence[str], None] = '16fb4bfba6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_trusts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_completed_rentals', sa.Integer(), nullable=False),
    sa.Column('on_time_returns', sa.Integer(), nullable=False),
    sa.Column('damage_free_returns', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_trusts_customer_id'), 'customer_trusts', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_trusts_organization_id'), 'customer_trusts', ['organization_id'], unique=False)
    op.create_table('trust_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_trust_id', sa.UUID(), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=True),
    sa.Column('old_score', sa.Integer(), nullable=False),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_trust_id'], ['customer_trusts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_history_customer_trust_id'), 'trust_history', ['customer_trust_id'], unique=False)
    op.create_index(op.f('ix_trust_history_organization_id'), 'trust_history', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_history_organization_id'), table_name='trust_history')
    op.drop_index(op.f('ix_trust_history_customer_trust_id'), table_name='trust_history')
    op.drop_table('trust_history')
    op.drop_index(op.f('ix_customer_trusts_organization_id'), table_name='customer_trusts')
    op.drop_index(op.f('ix_customer_trusts_customer_id'), table_name='customer_trusts')
    op.drop_table('customer_trusts')
    # ### end Alembic commands ###
