"""Add rentals

Revision ID: b92caa2a3e60
Revises: 874a2dea687b
Create Date: 2026-08-08 12:02:49.829807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92caa2a3e60'
down_revision: Union[str, Sequence[str], None] = '874a2dea687b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('rental_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'QUOTED', 'CONFIRMED', 'PAYMENT_PENDING', 'PAYMENT_COMPLETED', 'READY_FOR_PICKUP', 'PICKED_UP', 'ACTIVE', 'RETURN_DUE', 'OVERDUE', 'RETURNED', 'INSPECTION', 'SETTLEMENT', 'COMPLETED', 'CANCELLED', name='rentalstatus'), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_return_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_method', sa.Enum('IN_STORE', 'DELIVERY', name='pickupmethod'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'rental_number', name='uq_org_rental_number')
    )
    op.create_index(op.f('ix_rentals_customer_id'), 'rentals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rentals_expected_return_datetime'), 'rentals', ['expected_return_datetime'], unique=False)
    op.create_index(op.f('ix_rentals_organization_id'), 'rentals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rentals_rental_number'), 'rentals', ['rental_number'], unique=False)
    op.create_index(op.f('ix_rentals_start_datetime'), 'rentals', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_rentals_status'), 'rentals', ['status'], unique=False)
    op.create_table('rental_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rental_days', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['product_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_items_asset_id'), 'rental_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rental_items_product_id'), 'rental_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_rental_items_rental_id'), 'rental_items', ['rental_id'], unique=False)
    op.create_index(op.f('ix_rental_items_variant_id'), 'rental_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_items_variant_id'), table_name='rental_items')
    op.drop_index(op.f('ix_rental_items_rental_id'), table_name='rental_items')
    op.drop_index(op.f('ix_rental_items_product_id'), table_name='rental_items')
    op.drop_index(op.f('ix_rental_items_asset_id'), table_name='rental_items')
    op.drop_table('rental_items')
    op.drop_index(op.f('ix_rentals_status'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_start_datetime'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_rental_number'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_organization_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_expected_return_datetime'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_customer_id'), table_name='rentals')
    op.drop_table('rentals')
    # ### end Alembic commands ###
