"""Phase 5 financial core

Revision ID: cecb309ff3b8
Revises: b92caa2a3e60
Create Date: 2026-08-08 12:24:46.098660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cecb309ff3b8'
down_revision: Union[str, Sequence[str], None] = 'b92caa2a3e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('required_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('REQUIRED', 'PENDING', 'HELD', 'PARTIALLY_DEDUCTED', 'REFUND_PENDING', 'REFUNDED', 'SETTLED', name='depositstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_accounts_organization_id'), 'deposit_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deposit_accounts_rental_id'), 'deposit_accounts', ['rental_id'], unique=True)
    op.create_index(op.f('ix_deposit_accounts_status'), 'deposit_accounts', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.Enum('RENTAL', 'DEPOSIT', 'REFUND', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=True)
    op.create_index(op.f('ix_payments_rental_id'), 'payments', ['rental_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('deposit_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEPOSIT_COLLECTED', 'LATE_FEE_DEDUCTION', 'DAMAGE_DEDUCTION', 'MISSING_ITEM_DEDUCTION', 'OTHER_DEDUCTION', 'REFUND', 'ADJUSTMENT', name='ledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['deposit_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_ledger_entries_account_id'), 'deposit_ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_deposit_ledger_entries_organization_id'), 'deposit_ledger_entries', ['organization_id'], unique=False)
    op.add_column('rentals', sa.Column('security_deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'security_deposit_amount')
    op.drop_index(op.f('ix_deposit_ledger_entries_organization_id'), table_name='deposit_ledger_entries')
    op.drop_index(op.f('ix_deposit_ledger_entries_account_id'), table_name='deposit_ledger_entries')
    op.drop_table('deposit_ledger_entries')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_rental_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_deposit_accounts_status'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_rental_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_organization_id'), table_name='deposit_accounts')
    op.drop_table('deposit_accounts')
    # ### end Alembic commands ###
