"""multi_language_support

Revision ID: eed7e1e8d742
Revises: f432d774ca89
Create Date: 2026-08-08 15:03:53.884669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed7e1e8d742'
down_revision: Union[str, Sequence[str], None] = 'f432d774ca89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_organization_id'), 'notification_templates', ['organization_id'], unique=False)
    op.add_column('customers', sa.Column('preferred_language', sa.String(length=10), nullable=False, server_default='en'))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('customers', 'preferred_language')
    op.drop_index(op.f('ix_notification_templates_organization_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
